### ISSUE TITLE
Error in Parsing quantifier <x,y>

### ISSUE THREAD

**Issue by inishantgrover** [s3curityb3ast/windows_auditor#3]
![image](https://user-images.githubusercontent.com/5766789/34110979-4acab07a-e42e-11e7-8f65-14e64ac98d26.png)

Hi,

When I run the script in admin powershell, I get the above mentioned error.

Can you please help me in resolving this.

**My OS is Windows 8.1 fully patched.**

**Comment by s3curityb3ast** [comment]
HI 

can you Please provide your power shell version using below command
```
$PSVersionTable
```

**Comment by inishantgrover** [comment]
PS C:\Windows\System32\WindowsPowerShell\v1.0> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by s3curityb3ast** [comment]
HI Nishant this script is made and tested for version 2.0.

Please check whether below code is working for the old and some new version.

````

echo "1 Checks for Computer Configuration"
echo "1.1 Security Settings"
echo "1.1.1 Account Policies" > report.txt

echo "1.1.1.1 Set 'Account lockout threshold' to '5 invalid logon attempt(s)'" 
echo "Account lockout threshold Should be 5 OR LESS invalid logon attempt(s)'" >> audit.txt
$a = "Account lockout threshold >----------->> "
$b = net accounts | findstr /i /c:"lockout threshold"
$a += if ($b -match 5) {echo "compliance"} else {echo "Non compliance this value should be less than 5"}
write-output $a
```
And  let me know if its working i will provide you old script.

**Comment by inishantgrover** [comment]
Hi, There is still error in Line 550. The code you have provided is for line 8 to 17.
![2017-12-23 10_29_29-administrator_ powershell](https://user-images.githubusercontent.com/5766789/34317065-40afed16-e7cc-11e7-8ad2-30cecb13614c.png)

However when I replaced line 550, with the line in your code,
`$a += if ($b -match 5) {echo "compliance"} else {echo "Non compliance this value should be less than 5"}`

It worked. 

Can you check is this appropriate?

**Comment by s3curityb3ast** [comment]
HI Nishant,
Sorry for delay, if it worked then its fine, It may be compatibility  issue with your systems power-shell version  Thanks for Suggestion.

Cheers :+1:
